version: "3"

services:
  db:
    container_name: df-ecomm-db
    image: postgres:alpine
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./assets/pg-init.sql:/docker-entrypoint-initdb.d/init.sql
